// ═══════════════════════════════════════════
// Tutor Module — Adaptive Learning Engine + Chat
// ═══════════════════════════════════════════

const Tutor = {
  getAdaptiveDifficulty(data, domainId) {
    if (!domainId || domainId === 'all') {
      const total = data.questionsAnswered;
      if (total < 5) return 'easy';
      const pct = total > 0 ? data.questionsCorrect / total : 0;
      if (pct >= 0.85) return 'hard';
      if (pct >= 0.60) return 'medium';
      return 'easy';
    }
    const d = data.questionsByDomain[domainId];
    if (!d || d.total < 3) return 'easy';
    const pct = d.correct / d.total;
    if (pct >= 0.85) return 'hard';
    if (pct >= 0.60) return 'medium';
    return 'easy';
  },
  respond(userMessage, data) {
    var msg = userMessage.toLowerCase().trim();
    var totalAnswered = data.questionsAnswered || 0;
    var overallPct = totalAnswered > 0 ? Math.round((data.questionsCorrect / totalAnswered) * 100) : 0;
    var weakest = Analytics ? Analytics.getWeakest(data) : null;
    var weakName = weakest ? Lang.domainName(weakest) : (Lang.isEn() ? 'practice more' : 'practicar más');

    // OSPF troubleshooting
    if ((msg.indexOf('ospf') >= 0 || msg.indexOf('adyacen') >= 0) && (msg.indexOf('no funciona') >= 0 || msg.indexOf('problema') >= 0 || msg.indexOf('falla') >= 0 || msg.indexOf('error') >= 0 || msg.indexOf('por qué') >= 0)) {
      if (Lang.isEn()) {
        return '**🔧 OSPF Adjacency Troubleshooting**\n\nTo diagnose why two OSPF routers aren\'t forming adjacency, check these in order:\n\n**1. Are they on the same subnet?**\n`show ip interface brief` — The connected interfaces\' IPs must be on the same subnet.\n\n**2. Are they in the same OSPF area?**\n`show ip ospf interface` — The "Area" field must match on both ends.\n\n**3. Do the Hello/Dead timers match?**\nDefault on broadcast/P2P: Hello 10s, Dead 40s\nDefault on NBMA: Hello 30s, Dead 120s\nIf they don\'t match → `ip ospf hello-interval 10`\n\n**4. Do they have unique Router IDs?**\n`show ip ospf` — If two routers have the same RID, adjacency won\'t form.\n\n**5. Does MTU match?**\n`show interface` — MTU must be identical. If not → `ip mtu 1500` or `ip ospf mtu-ignore`\n\n**6. Authentication?**\nIf one has `ip ospf authentication message-digest`, the other must too.\n\n**7. Network type?**\nBroadcast, point-to-point, NBMA — must be compatible.\n`ip ospf network point-to-point`\n\n**Diagnostic commands:**\n`show ip ospf neighbor` — Is the neighbor visible? What state?\n`debug ip ospf adj` — Shows the adjacency process in real time';
      }
      return '**🔧 Troubleshooting de Adyacencia OSPF**\n\nPara diagnosticar por qué dos routers OSPF no forman vecindad, verificá esto en orden:\n\n**1. ¿Están en la misma subred?**\n`show ip interface brief` — Las IPs de las interfaces conectadas deben estar en la misma subred.\n\n**2. ¿Están en la misma área OSPF?**\n`show ip ospf interface` — El campo "Area" debe coincidir en ambos extremos.\n\n**3. ¿Los timers de Hello/Dead coinciden?**\nDefault en broadcast/P2P: Hello 10s, Dead 40s\nDefault en NBMA: Hello 30s, Dead 120s\nSi no coinciden → `ip ospf hello-interval 10`\n\n**4. ¿Tienen Router IDs únicos?**\n`show ip ospf` — Si dos routers tienen el mismo RID, la adyacencia no se forma.\n\n**5. ¿MTU coincide?**\n`show interface` — MTU debe ser idéntico. Si no → `ip mtu 1500` o `ip ospf mtu-ignore`\n\n**6. ¿Autenticación?**\nSi uno tiene `ip ospf authentication message-digest`, el otro también debe tenerla.\n\n**7. ¿Tipo de red?**\nBroadcast, point-to-point, NBMA — deben ser compatibles.\n`ip ospf network point-to-point`\n\n**Comandos de diagnóstico:**\n`show ip ospf neighbor` — ¿Aparece el vecino? ¿En qué estado está?\n`debug ip ospf adj` — Muestra el proceso de adyacencia en tiempo real';
    }

    // OSPF general
    if (msg.indexOf('ospf') >= 0) {
      if (Lang.isEn()) {
        return '**📡 OSPF (Open Shortest Path First)**\n\nLink-State routing protocol, open standard. AD = 110.\n\n**Key concepts:**\n• Uses the Dijkstra SPF algorithm to compute the best path\n• Multicast addresses: 224.0.0.5 (AllSPFRouters), 224.0.0.6 (AllDRouters)\n• Metric = Cost = Reference BW / Interface BW (default: 100 Mbps / BW)\n• Area 0 (Backbone) is mandatory\n\n**Basic configuration:**\n```\nrouter ospf 1\n router-id 1.1.1.1\n network 10.0.0.0 0.0.0.3 area 0\n```\n\n**Neighbor states:**\nDown → Init → 2-Way → ExStart → Exchange → Loading → Full\n\n**Important LSAs:**\n• Type 1: Router LSA (each router)\n• Type 2: Network LSA (generated by the DR)\n• Type 3: Summary LSA (ABR between areas)\n• Type 5: External LSA (ASBR, external routes)\n\n**O IA** in `show ip route` = inter-area route (learned from another area)';
      }
      return '**📡 OSPF (Open Shortest Path First)**\n\nProtocolo de enrutamiento Link-State, estándar abierto. AD = 110.\n\n**Conceptos clave:**\n• Usa el algoritmo Dijkstra SPF para calcular la mejor ruta\n• Direcciones multicast: 224.0.0.5 (AllSPFRouters), 224.0.0.6 (AllDRouters)\n• Métrica = Costo = BW referencia / BW interfaz (default: 100 Mbps / BW)\n• Área 0 (Backbone) es obligatoria\n\n**Configuración básica:**\n```\nrouter ospf 1\n router-id 1.1.1.1\n network 10.0.0.0 0.0.0.3 area 0\n```\n\n**Estados de vecino:**\nDown → Init → 2-Way → ExStart → Exchange → Loading → Full\n\n**LSAs importantes:**\n• Tipo 1: Router LSA (cada router)\n• Tipo 2: Network LSA (generada por el DR)\n• Tipo 3: Summary LSA (ABR entre áreas)\n• Tipo 5: External LSA (ASBR, rutas externas)\n\n**O IA** en `show ip route` = ruta inter-área (aprendida de otra área)';
    }

    // Subnetting
    if (msg.indexOf('subnet') >= 0 || msg.indexOf('subred') >= 0 || msg.indexOf('cidr') >= 0 || msg.indexOf('vlsm') >= 0 || msg.indexOf('máscara') >= 0) {
      if (Lang.isEn()) {
        return '**🧮 Subnetting — Quick Guide**\n\n**Essential formulas:**\n• Hosts per subnet = 2ⁿ - 2 (n = host bits)\n• Subnets created = 2ˢ (s = borrowed bits)\n• CIDR mask = 32 - n\n\n**Reference table:**\n```\n/24 = 256 IPs (254 hosts)  |  255.255.255.0\n/25 = 128 IPs (126 hosts)  |  255.255.255.128\n/26 = 64 IPs  (62 hosts)   |  255.255.255.192\n/27 = 32 IPs  (30 hosts)   |  255.255.255.224\n/28 = 16 IPs  (14 hosts)   |  255.255.255.240\n/29 = 8 IPs   (6 hosts)    |  255.255.255.248\n/30 = 4 IPs   (2 hosts)    |  255.255.255.252\n```\n\n**Quick example:** You need 50 hosts → 2ⁿ-2 ≥ 50 → n=6 → /26 (62 hosts)\n\n**Wildcard Mask (for ACLs and OSPF):**\nWildcard = 255.255.255.255 - mask\n/24 → wildcard 0.0.0.255\n/26 → wildcard 0.0.0.63\n\n**Private RFC 1918 addresses:**\n• 10.0.0.0/8\n• 172.16.0.0/12 (172.16.0.0 - 172.31.255.255)\n• 192.168.0.0/16\n\nWant me to throw a subnetting exercise your way to practice? 🎯';
      }
      return '**🧮 Subnetting — Guía Rápida**\n\n**Fórmulas esenciales:**\n• Hosts por subred = 2ⁿ - 2 (n = bits de host)\n• Subredes creadas = 2ˢ (s = bits prestados)\n• Máscara CIDR = 32 - n\n\n**Tabla de referencia:**\n```\n/24 = 256 IPs (254 hosts)  |  255.255.255.0\n/25 = 128 IPs (126 hosts)  |  255.255.255.128\n/26 = 64 IPs  (62 hosts)   |  255.255.255.192\n/27 = 32 IPs  (30 hosts)   |  255.255.255.224\n/28 = 16 IPs  (14 hosts)   |  255.255.255.240\n/29 = 8 IPs   (6 hosts)    |  255.255.255.248\n/30 = 4 IPs   (2 hosts)    |  255.255.255.252\n```\n\n**Ejemplo rápido:** Necesitás 50 hosts → 2ⁿ-2 ≥ 50 → n=6 → /26 (62 hosts)\n\n**Wildcard Mask (para ACLs y OSPF):**\nWildcard = 255.255.255.255 - máscara\n/24 → wildcard 0.0.0.255\n/26 → wildcard 0.0.0.63\n\n**Direcciones privadas RFC 1918:**\n• 10.0.0.0/8\n• 172.16.0.0/12 (172.16.0.0 - 172.31.255.255)\n• 192.168.0.0/16\n\n¿Querés que te tire un ejercicio de subnetting para practicar? 🎯';
    }

    // STP
    if (msg.indexOf('stp') >= 0 || msg.indexOf('spanning tree') >= 0 || msg.indexOf('root bridge') >= 0 || msg.indexOf('bpdu') >= 0) {
      if (Lang.isEn()) {
        return '**🌲 Spanning Tree Protocol (STP)**\n\nPrevents Layer 2 loops by blocking redundant ports.\n\n**How it works:**\n1. A **Root Bridge** is elected (lowest Bridge ID = Priority + MAC)\n2. Each non-root switch elects its **Root Port** (lowest cost to Root)\n3. A **Designated Port** is elected on each segment\n4. Ports that aren\'t Root or Designated → **Blocking**\n\n**Port states (classic STP):**\nBlocking (20s) → Listening (15s) → Learning (15s) → Forwarding\n\n**Versions:**\n• **STP (802.1D):** Original, 30-50s convergence\n• **RSTP (802.1w):** Fast convergence ~2s\n• **PVST+:** Cisco, 1 instance per VLAN\n• **MSTP (802.1s):** Groups VLANs into instances\n\n**Key commands:**\n`spanning-tree vlan 1 root primary` → Forces Root Bridge election\n`spanning-tree portfast` → Skips listening/learning on access ports\n`spanning-tree bpduguard enable` → Shuts down port if BPDU received\n\n**PortFast + BPDU Guard:** ALWAYS use together on access ports for endpoints.';
      }
      return '**🌲 Spanning Tree Protocol (STP)**\n\nPreviene bucles de Capa 2 bloqueando puertos redundantes.\n\n**Cómo funciona:**\n1. Se elige un **Root Bridge** (Bridge ID más bajo = Prioridad + MAC)\n2. Cada switch no-root elige su **Root Port** (menor costo al Root)\n3. En cada segmento se elige un **Designated Port**\n4. Los puertos que no son Root ni Designated → **Blocking**\n\n**Estados de puerto (STP clásico):**\nBlocking (20s) → Listening (15s) → Learning (15s) → Forwarding\n\n**Versiones:**\n• **STP (802.1D):** Original, 30-50s convergencia\n• **RSTP (802.1w):** Convergencia rápida ~2s\n• **PVST+:** Cisco, 1 instancia por VLAN\n• **MSTP (802.1s):** Agrupa VLANs en instancias\n\n**Comandos clave:**\n`spanning-tree vlan 1 root primary` → Fuerza Root Bridge\n`spanning-tree portfast` → Salta listening/learning en puertos de acceso\n`spanning-tree bpduguard enable` → Apaga puerto si recibe BPDU\n\n**PortFast + BPDU Guard:** Usar SIEMPRE juntos en puertos de acceso para endpoints.';
    }

    // VLANs
    if (msg.indexOf('vlan') >= 0 && msg.indexOf('acl') < 0) {
      if (Lang.isEn()) {
        return '**🔖 VLANs and Trunking**\n\n**VLAN (Virtual LAN):** Layer 2 logical segmentation. Each VLAN = independent broadcast domain.\n\n**Ranges:**\n• Normal: 1-1005 (VLAN 1 = default, cannot be deleted)\n• Extended: 1006-4094 (requires VTP transparent mode)\n\n**Configuration:**\n```\n! Create VLAN\nvlan 10\n name DATA\n\n! Access port\ninterface Gi0/1\n switchport mode access\n switchport access vlan 10\n\n! 802.1Q Trunk\ninterface Gi0/24\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30  (optional)\n```\n\n**Native VLAN:** Untagged traffic on the trunk. Default VLAN 1. ⚠️ Must match on both ends.\n\n**Verification:**\n`show vlan brief` — Lists VLANs and assigned ports\n`show interfaces trunk` — Shows trunks, allowed VLANs, native VLAN\n`show interfaces Gi0/1 switchport` — Port detail\n\n**DTP (Dynamic Trunking Protocol):** Auto-negotiates trunks. Modes: dynamic auto, dynamic desirable. ⚠️ Best practice: disable DTP (`switchport nonegotiate`).';
      }
      return '**🔖 VLANs y Trunking**\n\n**VLAN (Virtual LAN):** Segmentación lógica de Capa 2. Cada VLAN = dominio de broadcast independiente.\n\n**Rangos:**\n• Normal: 1-1005 (VLAN 1 = default, no eliminable)\n• Extendido: 1006-4094 (requiere VTP transparente)\n\n**Configuración:**\n```\n! Crear VLAN\nvlan 10\n name DATA\n\n! Puerto de acceso\ninterface Gi0/1\n switchport mode access\n switchport access vlan 10\n\n! Trunk 802.1Q\ninterface Gi0/24\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30  (opcional)\n```\n\n**VLAN Nativa:** Tráfico sin etiquetar en el trunk. Default VLAN 1. ⚠️ Debe coincidir en ambos extremos.\n\n**Verificación:**\n`show vlan brief` — Lista VLANs y puertos asignados\n`show interfaces trunk` — Muestra trunks, VLANs permitidas, VLAN nativa\n`show interfaces Gi0/1 switchport` — Detalle de un puerto\n\n**DTP (Dynamic Trunking Protocol):** Negocia trunks automáticamente. Modos: dynamic auto, dynamic desirable. ⚠️ Mejor práctica: deshabilitar DTP (`switchport nonegotiate`).';
    }

    // ACLs
    if (msg.indexOf('acl') >= 0 || msg.indexOf('access list') >= 0 || msg.indexOf('access-list') >= 0) {
      if (Lang.isEn()) {
        return '**🛡️ Access Control Lists (ACLs)**\n\n**Types:**\n• **Standard (1-99, 1300-1999):** Filters by SOURCE IP only\n• **Extended (100-199, 2000-2699):** Source IP + destination + protocol + ports\n\n**⚠️ Golden rule:** ACLs are processed in order (top-down) and have an implicit **deny any any** at the end. If there isn\'t at least one \"permit\", all traffic is blocked.\n\n**They use WILDCARD MASK (inverted mask):**\n/24 → wildcard 0.0.0.255\n/26 → wildcard 0.0.0.63\n\n**Examples:**\n```\n! Allow only HTTP from local network\naccess-list 100 permit tcp 192.168.1.0 0.0.0.255 any eq 80\naccess-list 100 deny ip any any\n\n! Block a specific host\naccess-list 1 deny host 192.168.1.100\naccess-list 1 permit any\n```\n\n**Apply to interface:**\n`ip access-group 100 in` (inbound) or `out` (outbound)\n\n**\"established\":** Only allows TCP traffic with ACK/RST flags (responses). Basic stateful firewall.\n\n**Named ACLs (recommended):**\n`ip access-list extended WEB-FILTER`\nAllows editing individual entries without rewriting the entire list.';
      }
return '**🛡️ Access Control Lists (ACLs)**\n\n**Tipos:**\n• **Estándar (1-99, 1300-1999):** Filtra SOLO por IP origen\n• **Extendida (100-199, 2000-2699):** IP origen + destino + protocolo + puertos\n\n**⚠️ Regla de oro:** Las ACLs se procesan en orden (top-down) y tienen un **deny any any implícito** al final. Si no hay al menos un "permit", todo el tráfico se bloquea.\n\n**Usan WILDCARD MASK (máscara invertida):**\n/24 → wildcard 0.0.0.255\n/26 → wildcard 0.0.0.63\n\n**Ejemplos:**\n```\n! Permitir solo HTTP desde red local\naccess-list 100 permit tcp 192.168.1.0 0.0.0.255 any eq 80\naccess-list 100 deny ip any any\n\n! Bloquear un host específico\naccess-list 1 deny host 192.168.1.100\naccess-list 1 permit any\n```\n\n**Aplicar a interfaz:**\n`ip access-group 100 in` (entrada) o `out` (salida)\n\n**"established":** Permite solo tráfico TCP con flags ACK/RST (respuestas). Firewall stateful básico.\n\n**ACLs nombradas (recomendado):**\n`ip access-list extended WEB-FILTER`\nPermite editar entradas individuales sin reescribir toda la lista.';
    }

    // DHCP
    if (msg.indexOf('dhcp') >= 0) {
      if (Lang.isEn()) {
        return '**📡 DHCP (Dynamic Host Configuration Protocol)**\n\nPorts: UDP 67 (server), UDP 68 (client)\nProcess: **DORA** — Discover → Offer → Request → Acknowledge\n\n**Configure DHCP server on Cisco router:**\n```\nip dhcp excluded-address 192.168.1.1 192.168.1.10\nip dhcp pool LAN\n network 192.168.1.0 255.255.255.0\n default-router 192.168.1.1\n dns-server 8.8.8.8 1.1.1.1\n lease 7\n```\n\n**DHCP Relay (IP Helper):**\nWhen the DHCP server is on another subnet:\n`ip helper-address 10.0.0.5` (on the client-facing interface)\n\n**DHCP Snooping (security):**\nPrevents rogue DHCP servers:\n```\nip dhcp snooping\nip dhcp snooping vlan 10,20\ninterface Gi0/1\n ip dhcp snooping trust   (port toward the legitimate DHCP server)\n```\n\n**Verification:**\n`show ip dhcp binding` — Active leases\n`show ip dhcp pool` — Pool utilization\n`show ip dhcp conflict` — Detected conflicts';
      }
      return '**📡 DHCP (Dynamic Host Configuration Protocol)**\n\nPuertos: UDP 67 (servidor), UDP 68 (cliente)\nProceso: **DORA** — Discover → Offer → Request → Acknowledgment\n\n**Configurar servidor DHCP en router Cisco:**\n```\nip dhcp excluded-address 192.168.1.1 192.168.1.10\nip dhcp pool LAN\n network 192.168.1.0 255.255.255.0\n default-router 192.168.1.1\n dns-server 8.8.8.8 1.1.1.1\n lease 7\n```\n\n**DHCP Relay (IP Helper):**\nCuando el servidor DHCP está en otra subred:\n`ip helper-address 10.0.0.5` (en la interfaz del cliente)\n\n**DHCP Snooping (seguridad):**\nPreviene servidores DHCP rogue:\n```\nip dhcp snooping\nip dhcp snooping vlan 10,20\ninterface Gi0/1\n ip dhcp snooping trust   (puerto hacia el DHCP legítimo)\n```\n\n**Verificación:**\n`show ip dhcp binding` — Leases activos\n`show ip dhcp pool` — Utilización del pool\n`show ip dhcp conflict` — Conflictos detectados';
    }

    // NAT
    if (msg.indexOf('nat') >= 0 || msg.indexOf('pat') >= 0) {
      if (Lang.isEn()) {
        return '**🔄 NAT (Network Address Translation)**\n\n**Types:**\n• **Static NAT:** 1 private IP ↔ 1 public IP (servers)\n• **Dynamic NAT:** Pool of public IPs for private IPs\n• **PAT (NAT Overload):** Many private IPs → 1 public IP (different ports)\n\n**Static NAT configuration:**\n```\ninterface Gi0/0\n ip nat inside\ninterface Gi0/1\n ip nat outside\nip nat inside source static 192.168.1.10 203.0.113.10\n```\n\n**PAT configuration (most common):**\n```\naccess-list 1 permit 192.168.1.0 0.0.0.255\nip nat inside source list 1 interface Gi0/1 overload\n```\n\n**Verification:**\n`show ip nat translations` — Active translations\n`show ip nat statistics` — Statistics\n\n**⚠️ For the CCNA:** Knowing how to configure PAT with `overload` is essential.';
      }
      return '**🔄 NAT (Network Address Translation)**\n\n**Tipos:**\n• **Static NAT:** 1 IP privada ↔ 1 IP pública (servidores)\n• **Dynamic NAT:** Pool de IPs públicas para IPs privadas\n• **PAT (NAT Overload):** Muchas IPs privadas → 1 IP pública (diferentes puertos)\n\n**Configuración Static NAT:**\n```\ninterface Gi0/0\n ip nat inside\ninterface Gi0/1\n ip nat outside\nip nat inside source static 192.168.1.10 203.0.113.10\n```\n\n**Configuración PAT (más común):**\n```\naccess-list 1 permit 192.168.1.0 0.0.0.255\nip nat inside source list 1 interface Gi0/1 overload\n```\n\n**Verificación:**\n`show ip nat translations` — Traducciones activas\n`show ip nat statistics` — Estadísticas\n\n**⚠️ Para el CCNA:** Saber configurar PAT con `overload` es fundamental.';
    }

    // EtherChannel
    if (msg.indexOf('etherchannel') >= 0 || msg.indexOf('lacp') >= 0 || msg.indexOf('pagp') >= 0 || msg.indexOf('port-channel') >= 0) {
      if (Lang.isEn()) {
        return '**🔗 EtherChannel**\n\nGroups up to 8 physical links into 1 logical link (Port-Channel).\n\n**Benefits:**\n• Increases bandwidth (up to 8x)\n• Redundancy (if one link fails, traffic is redistributed)\n• STP sees the Port-Channel as a single link\n\n**Negotiation protocols:**\n• **LACP (IEEE 802.3ad):** Standard. Modes: active/passive\n• **PAgP:** Cisco proprietary. Modes: desirable/auto\n• **ON:** No negotiation (both sides forced)\n\n**LACP configuration:**\n```\ninterface range Gi0/1-4\n channel-group 1 mode active\n```\n\n**⚠️ Requirements:** All ports in the bundle must match on:\nSpeed, duplex, VLAN mode (access/trunk), allowed VLANs, STP config.\n\n**Verification:**\n`show etherchannel summary`\n`show etherchannel port-channel`';
      }
      return '**🔗 EtherChannel**\n\nAgrupa hasta 8 enlaces físicos en 1 lógico (Port-Channel).\n\n**Beneficios:**\n• Aumenta ancho de banda (hasta 8x)\n• Redundancia (si un enlace falla, el tráfico se redistribuye)\n• STP ve el Port-Channel como un solo enlace\n\n**Protocolos de negociación:**\n• **LACP (IEEE 802.3ad):** Estándar. Modos: active/passive\n• **PAgP:** Cisco propietario. Modos: desirable/auto\n• **ON:** Sin negociación (ambos lados forzados)\n\n**Configuración LACP:**\n```\ninterface range Gi0/1-4\n channel-group 1 mode active\n```\n\n**⚠️ Requisitos:** Todos los puertos del bundle deben coincidir en:\nSpeed, duplex, VLAN mode (access/trunk), VLANs permitidas, STP config.\n\n**Verificación:**\n`show etherchannel summary`\n`show etherchannel port-channel`';
    }

    // Port Security
    if (msg.indexOf('port security') >= 0 || msg.indexOf('port-security') >= 0 || msg.indexOf('errdisable') >= 0) {
      if (Lang.isEn()) {
        return '**🔒 Port Security**\n\nLimits which MAC addresses can connect to a switch port.\n\n**Typical configuration:**\n```\ninterface Gi0/1\n switchport mode access\n switchport port-security\n switchport port-security maximum 2\n switchport port-security mac-address sticky\n switchport port-security violation restrict\n```\n\n**Violation modes:**\n• **Shutdown (default):** Shuts down the port (err-disable). Requires `shutdown` + `no shutdown`\n• **Restrict:** Drops packets from unauthorized MACs + sends SNMP trap\n• **Protect:** Silently drops packets only\n\n**Sticky MAC:** Automatically learns the MAC and saves it to running-config.\n\n**Recover from err-disable:**\n`errdisable recovery cause psecure-violation`\n`errdisable recovery interval 300`\n\n**Verification:**\n`show port-security`\n`show port-security interface Gi0/1`\n`show port-security address`';
      }
      return '**🔒 Port Security**\n\nLimita qué MACs pueden conectarse a un puerto de switch.\n\n**Configuración típica:**\n```\ninterface Gi0/1\n switchport mode access\n switchport port-security\n switchport port-security maximum 2\n switchport port-security mac-address sticky\n switchport port-security violation restrict\n```\n\n**Modos de violación:**\n• **Shutdown (default):** Apaga el puerto (err-disable). Requiere `shutdown` + `no shutdown`\n• **Restrict:** Descarta paquetes de MACs no autorizadas + envía SNMP trap\n• **Protect:** Solo descarta paquetes (silencioso)\n\n**Sticky MAC:** Aprende la MAC automáticamente y la guarda en running-config.\n\n**Recuperar de err-disable:**\n`errdisable recovery cause psecure-violation`\n`errdisable recovery interval 300`\n\n**Verificación:**\n`show port-security`\n`show port-security interface Gi0/1`\n`show port-security address`';
    }

    // Exam readiness
    if (msg.indexOf('examen') >= 0 || msg.indexOf('preparar') >= 0 || msg.indexOf('aprobar') >= 0 || msg.indexOf('listo') >= 0 || msg.indexOf('ready') >= 0 || msg.indexOf('estudiar') >= 0 || msg.indexOf('puntaje') >= 0) {
      var examCount = data.examsTaken ? data.examsTaken.length : 0;
      var statusMsg = '';
      if (overallPct >= 83) {
        statusMsg = Lang.isEn() ? '🔥 **You\'re in passing territory.** Keep practicing with mock exams.' : '🔥 **Estás en zona de aprobación.** Mantené la práctica con simulacros.';
      } else if (overallPct >= 60) {
        statusMsg = Lang.isEn() ? '📈 **Good progress** but you need to reinforce. Your weakest area is **' + weakName + '** — focus there.' : '📈 **Vas bien** pero necesitás reforzar. Tu área más débil es **' + weakName + '** — enfocate ahí.';
      } else {
        statusMsg = Lang.isEn() ? '📚 **Still work to do.** Start with **' + weakName + '** and take at least 3-5 full practice exams.' : '📚 **Todavía hay trabajo por hacer.** Empezá por **' + weakName + '** y hacé al menos 3-5 simulacros completos.';
      }

      if (Lang.isEn()) {
        return '**📋 CCNA 200-301 v2.0 Exam Preparation**\n\n**Exam structure:**\n• 120-minute exam\n• Passing score: ~825/1000 (approximately 82-83%)\n• No penalty for incorrect answers\n\n**Topic distribution (2026):**\n1. 🌐 Network Infrastructure and Connectivity (25%) — Cabling, VMs/containers, IPv4/IPv6, wireless, DHCP\n2. 🔌 Switching and Network Access (25%) — VLANs, STP/Rapid-PVST+, EtherChannel, CDP/LLDP\n3. 🔗 IP Routing (20%) — OSPFv2/v3, static routes, FHRP (HSRP+VRRP)\n4. 🔒 Network Services and Security (20%) — AAA, ACLs, NAT/PAT, VPN, L2 security, DNS\n5. 🤖 AI, and Network Operations (10%) — Agentic AI, genAI prompts, SNMP, Ansible, syslog\n\n**Your current progress:**\n• ' + totalAnswered + ' questions answered\n• Overall accuracy: ' + overallPct + '%\n• ' + examCount + ' practice exams completed\n\n' + statusMsg + '\n\n**Tip:** Take practice exams in similar conditions to the real exam: 90-120 minutes with no interruptions or distractions.';
      }
      return '**📋 Preparación para el CCNA 200-301 v2.0**\n\n**Estructura del examen:**\n• Examen de 120 minutos\n• Puntaje de corte: ~825/1000 (aproximadamente 82-83%)\n• Sin penalización por respuestas incorrectas\n\n**Distribución de temas (2026):**\n1. 🌐 Infraestructura y Conectividad de Red (25%) — Cableado, VMs/containers, IPv4/IPv6, wireless, DHCP\n2. 🔌 Switching y Acceso a la Red (25%) — VLANs, STP/Rapid-PVST+, EtherChannel, CDP/LLDP\n3. 🔗 Enrutamiento IP (20%) — OSPFv2/v3, rutas estáticas, FHRP (HSRP+VRRP)\n4. 🔒 Servicios y Seguridad de Red (20%) — AAA, ACLs, NAT/PAT, VPN, seguridad L2, DNS\n5. 🤖 IA y Operaciones de Red (10%) — IA agéntica, prompts generativos, SNMP, Ansible, syslog\n\n**Tu progreso actual:**\n• ' + totalAnswered + ' preguntas respondidas\n• Precisión general: ' + overallPct + '%\n• ' + examCount + ' simulacros completados\n\n' + statusMsg + '\n\n**Tip:** Hacé simulacros en condiciones similares al examen real: 90-120 minutos sin interrupciones ni distracciones.';
    }

    // General CCNA concepts
    if (msg.indexOf('capa') >= 0 || msg.indexOf('modelo osi') >= 0 || msg.indexOf('tcp/ip') >= 0) {
      if (Lang.isEn()) {
        return '**🏗️ OSI Model (7 Layers)**\n\nBottom to top:\n1. **Physical:** Bits, cables, hubs. Standards: RJ-45, 802.11 WiFi\n2. **Data Link:** Frames, MAC, switches. Protocols: Ethernet, PPP\n3. **Network:** Packets, IP, routers. Protocols: IPv4, IPv6, ICMP\n4. **Transport:** Segments, TCP/UDP. Ports, flow control\n5. **Session:** Establishes/maintains/terminates sessions\n6. **Presentation:** Formatting, encryption (SSL/TLS), compression\n7. **Application:** HTTP, FTP, DNS, SMTP, SSH\n\n**PDU by layer:**\nBits (L1) → Frames (L2) → Packets (L3) → Segments (L4) → Data (L5-7)\n\n**TCP/IP Model (4 Layers):**\nNetwork Access → Internet → Transport → Application';
      }
      return '**🏗️ Modelo OSI (7 capas)**\n\nDe abajo hacia arriba:\n1. **Física:** Bits, cables, hubs. Estándares: RJ-45, 802.11 WiFi\n2. **Enlace de Datos:** Tramas, MAC, switches. Protocolos: Ethernet, PPP\n3. **Red:** Paquetes, IP, routers. Protocolos: IPv4, IPv6, ICMP\n4. **Transporte:** Segmentos, TCP/UDP. Puertos, control de flujo\n5. **Sesión:** Establece/mantiene/termina sesiones\n6. **Presentación:** Formato, cifrado (SSL/TLS), compresión\n7. **Aplicación:** HTTP, FTP, DNS, SMTP, SSH\n\n**PDU por capa:**\nBits (L1) → Tramas (L2) → Paquetes (L3) → Segmentos (L4) → Datos (L5-7)\n\n**Modelo TCP/IP (4 capas):**\nAcceso a Red → Internet → Transporte → Aplicación';
    }

    // EIGRP
    if (msg.indexOf('eigrp') >= 0) {
      if (Lang.isEn()) {
        return '**🚀 EIGRP (Enhanced Interior Gateway Routing Protocol)**\n\nHybrid protocol (advanced distance-vector) proprietary to Cisco.\nAD: 90 (internal), 170 (external)\nMulticast: 224.0.0.10\n\n**Tables:**\n• Neighbor Table: EIGRP neighbors\n• Topology Table: All learned routes\n• Routing Table: Best routes (Successors)\n\n**Composite metric:** Bandwidth + Delay (default K values)\nFormula: 256 * (BW + Delay)\n\n**Basic configuration:**\n```\nrouter eigrp 100\n network 10.0.0.0 0.0.0.3\n no auto-summary\n```\n\n**Verification:**\n`show ip eigrp neighbors`\n`show ip eigrp topology`\n`show ip route eigrp`';
      }
      return '**🚀 EIGRP (Enhanced Interior Gateway Routing Protocol)**\n\nProtocolo híbrido (vector-distancia avanzado) propietario de Cisco.\nAD: 90 (interno), 170 (externo)\nMulticast: 224.0.0.10\n\n**Tablas:**\n• Neighbor Table: Vecinos EIGRP\n• Topology Table: Todas las rutas aprendidas\n• Routing Table: Mejores rutas (Sucesores)\n\n**Métrica compuesta:** Ancho de banda + Delay (default K values)\nFórmula: 256 * (BW + Delay)\n\n**Configuración básica:**\n```\nrouter eigrp 100\n network 10.0.0.0 0.0.0.3\n no auto-summary\n```\n\n**Verificación:**\n`show ip eigrp neighbors`\n`show ip eigrp topology`\n`show ip route eigrp`';
    }

    // HSRP / FHRP
    if (msg.indexOf('hsrp') >= 0 || msg.indexOf('vrrp') >= 0 || msg.indexOf('glbp') >= 0 || msg.indexOf('fhrp') >= 0) {
      if (Lang.isEn()) {
        return '**🔄 FHRP — First Hop Redundancy Protocols**\n\nProvide gateway redundancy (virtual default gateway).\n\n**HSRP (Cisco proprietary):**\n• 1 Active router, 1+ Standby\n• Virtual IP + Virtual MAC (0000.0c07.acXX)\n• Multicast: 224.0.0.2 (v1) / 224.0.0.102 (v2)\n• Default priority: 100. Higher = better\n• `standby 1 preempt` → Allows taking the Active role\n\n**VRRP (Standard RFC 5798):**\n• Similar to HSRP\n• Multicast: 224.0.0.18\n• Default priority: 100. Higher = better\n• Preempt enabled by default\n\n**GLBP (Cisco proprietary):**\n• Load balancing + redundancy\n• 1 AVG (Active Virtual Gateway) + up to 4 AVFs\n• Different virtual MACs to balance traffic\n\n**HSRP configuration:**\n```\ninterface Gi0/0\n standby 1 ip 192.168.1.254\n standby 1 priority 110\n standby 1 preempt\n```\n\n**Verification:**\n`show standby` — HSRP state\n`show standby brief`';
      }
      return '**🔄 FHRP — First Hop Redundancy Protocols**\n\nProporcionan redundancia de gateway (default gateway virtual).\n\n**HSRP (Cisco propietario):**\n• 1 router Active, 1+ Standby\n• IP virtual + MAC virtual (0000.0c07.acXX)\n• Multicast: 224.0.0.2 (v1) / 224.0.0.102 (v2)\n• Prioridad default: 100. Mayor = mejor\n• `standby 1 preempt` → Permite tomar el rol Active\n\n**VRRP (Estándar RFC 5798):**\n• Similar a HSRP\n• Multicast: 224.0.0.18\n• Prioridad default: 100. Mayor = mejor\n• Preempt habilitado por defecto\n\n**GLBP (Cisco propietario):**\n• Balanceo de carga + redundancia\n• 1 AVG (Active Virtual Gateway) + hasta 4 AVFs\n• Diferentes MACs virtuales para balancear tráfico\n\n**Configuración HSRP:**\n```\ninterface Gi0/0\n standby 1 ip 192.168.1.254\n standby 1 priority 110\n standby 1 preempt\n```\n\n**Verificación:**\n`show standby` — Estado HSRP\n`show standby brief`';
    }

    // Automation / SDN
    if (msg.indexOf('api') >= 0 || msg.indexOf('rest') >= 0 || msg.indexOf('json') >= 0 || msg.indexOf('ansible') >= 0 || msg.indexOf('sdn') >= 0 || msg.indexOf('dna') >= 0 || msg.indexOf('automat') >= 0) {
      if (Lang.isEn()) {
        return '**🤖 Automation and Programmability**\n\n**REST APIs:**\n• GET: Read data\n• POST: Create resources\n• PUT: Update resources\n• DELETE: Delete resources\n• Codes: 200 OK, 201 Created, 401 Unauthorized, 404 Not Found\n\n**Data formats:**\n• **JSON:** Most common in modern APIs. `{\"key\": \"value\"}`\n• **XML:** Used in NETCONF. More verbose\n• **YAML:** Ansible, configurations. Human-readable\n\n**Tools:**\n• **Ansible:** Agentless, SSH, YAML playbooks, Cisco IOS modules\n• **Puppet:** Agent-based, own DSL, pull model\n• **Chef:** Ruby, cookbooks and recipes\n\n**SDN / Cisco:**\n• **DNA Center:** Controller for campus/enterprise\n• **ACI (APIC):** Data center, contract-based policies\n• **vManage:** SD-WAN (now Catalyst SD-WAN)\n\n**NETCONF / YANG:**\n• YANG: Data model\n• NETCONF: XML protocol over SSH (port 830)\n• RESTCONF: RESTful API over HTTP';
      }
return '**🤖 Automatización y Programabilidad**\n\n**APIs REST:**\n• GET: Leer datos\n• POST: Crear recursos\n• PUT: Actualizar recursos\n• DELETE: Eliminar recursos\n• Códigos: 200 OK, 201 Created, 401 Unauthorized, 404 Not Found\n\n**Formatos de datos:**\n• **JSON:** El más común en APIs modernas. `{"key": "value"}`\n• **XML:** Usado en NETCONF. Más verboso\n• **YAML:** Ansible, configuraciones. Legible por humanos\n\n**Herramientas:**\n• **Ansible:** Agentless, SSH, playbooks YAML, módulos Cisco IOS\n• **Puppet:** Agente, DSL propio, modelo pull\n• **Chef:** Ruby, cookbooks y recipes\n\n**SDN / Cisco:**\n• **DNA Center:** Controladora para campus/enterprise\n• **ACI (APIC):** Data center, políticas basadas en contratos\n• **vManage:** SD-WAN (ahora Catalyst SD-WAN)\n\n**NETCONF / YANG:**\n• YANG: Modelo de datos\n• NETCONF: Protocolo XML sobre SSH (puerto 830)\n• RESTCONF: API RESTful sobre HTTP';
    }

    // IPv6
    if (msg.indexOf('ipv6') >= 0) {
      if (Lang.isEn()) {
        return '**🌐 IPv6**\n\n**128-bit addresses** (8 groups of 4 hex digits).\nExample: `2001:0db8:0000:0000:0000:ff00:0042:8329`\nShortened: `2001:db8::ff00:42:8329`\n\n**Types:**\n• **Unicast:** Global (2000::/3), Link-Local (FE80::/10), Unique Local (FC00::/7)\n• **Multicast:** FF00::/8\n• **Anycast:** One-to-one (nearest)\n\n**No broadcast in IPv6.** Replaced by multicast.\n\n**Loopback:** ::1/128\n**Unspecified:** ::/128\n\n**Cisco configuration:**\n```\ninterface Gi0/0\n ipv6 address 2001:db8:1::1/64\n ipv6 enable   (link-local only)\n```\n\n**OSPFv3 for IPv6:**\n`ipv6 router ospf 1`\n`ipv6 ospf 1 area 0` (on the interface)\n\n**Verification:**\n`show ipv6 interface brief`\n`show ipv6 route`';
      }
      return '**🌐 IPv6**\n\n**Direcciones de 128 bits** (8 grupos de 4 hex dígitos).\nEjemplo: `2001:0db8:0000:0000:0000:ff00:0042:8329`\nAbreviado: `2001:db8::ff00:42:8329`\n\n**Tipos:**\n• **Unicast:** Global (2000::/3), Link-Local (FE80::/10), Unique Local (FC00::/7)\n• **Multicast:** FF00::/8\n• **Anycast:** Uno a uno (el más cercano)\n\n**No hay broadcast en IPv6.** Se reemplaza por multicast.\n\n**Loopback:** ::1/128\n**No especificada:** ::/128\n\n**Configuración en Cisco:**\n```\ninterface Gi0/0\n ipv6 address 2001:db8:1::1/64\n ipv6 enable   (solo link-local)\n```\n\n**OSPFv3 para IPv6:**\n`ipv6 router ospf 1`\n`ipv6 ospf 1 area 0` (en la interfaz)\n\n**Verificación:**\n`show ipv6 interface brief`\n`show ipv6 route`';
    }

    // SSH / Security
    if (msg.indexOf('ssh') >= 0 || msg.indexOf('telnet') >= 0 || msg.indexOf('seguridad') >= 0 || msg.indexOf('aaa') >= 0) {
      if (Lang.isEn()) {
        return '**🔐 Secure Device Access**\n\n**SSH vs Telnet:**\n• **SSH:** Encrypted, TCP port 22. Requires RSA keys\n• **Telnet:** Plain text, TCP port 23. ⚠️ Do not use in production\n\n**Configure SSH on router:**\n```\nhostname R1\nip domain-name example.com\ncrypto key generate rsa modulus 2048\nip ssh version 2\nline vty 0 4\n transport input ssh\n login local\nusername admin secret MyPassword123\n```\n\n**enable secret vs enable password:**\n• `enable secret`: SHA-256 hash (type 5/8). Secure. ✅\n• `enable password`: Type 7 encryption (Vigenère). Reversible. ❌\n• `service password-encryption`: Only applies weak type 7\n\n**AAA (Authentication, Authorization, Accounting):**\n• **TACACS+:** Cisco, TCP 49, encrypts everything, separates AAA\n• **RADIUS:** Standard, UDP 1812/1813, only encrypts password\n\n**Basic AAA configuration:**\n```\naaa new-model\naaa authentication login default local\naaa authorization exec default local\n```';
      }
      return '**🔐 Acceso Seguro al Dispositivo**\n\n**SSH vs Telnet:**\n• **SSH:** Cifrado, puerto TCP 22. Requiere claves RSA\n• **Telnet:** Texto plano, puerto TCP 23. ⚠️ No usar en producción\n\n**Configurar SSH en router:**\n```\nhostname R1\nip domain-name ejemplo.com\ncrypto key generate rsa modulus 2048\nip ssh version 2\nline vty 0 4\n transport input ssh\n login local\nusername admin secret MiPassword123\n```\n\n**enable secret vs enable password:**\n• `enable secret`: Hash SHA-256 (tipo 5/8). Seguro. ✅\n• `enable password`: Cifrado tipo 7 (Vigenère). Reversible. ❌\n• `service password-encryption`: Solo aplica tipo 7 débil\n\n**AAA (Authentication, Authorization, Accounting):**\n• **TACACS+:** Cisco, TCP 49, cifra todo, separa AAA\n• **RADIUS:** Estándar, UDP 1812/1813, solo cifra password\n\n**Configuración AAA básica:**\n```\naaa new-model\naaa authentication login default local\naaa authorization exec default local\n```';
    }

    // Default contextual response
    if (totalAnswered < 5) {
      if (Lang.isEn()) {
        return '👋 **Still early days!** I recommend starting by answering questions in **Practice** mode — that way I can identify your strengths and weaknesses.\n\n**To get started right away:**\n• Go to the **📝 Practice** tab\n• Select "Network Fundamentals" (it\'s the foundation of everything)\n• Choose "Easy" difficulty to start\n\nWant me to explain a specific topic in the meantime? You can ask me about OSPF, subnetting, VLANs, STP, ACLs... whatever you need! 🚀';
      }
      return '👋 **Todavía estamos en etapa temprana.** Te recomiendo empezar respondiendo preguntas en modo **Práctica** — así puedo identificar tus fortalezas y debilidades.\n\n**Para arrancar ya mismo:**\n• Andá a la pestaña **📝 Practicar**\n• Seleccioná "Fundamentos de Red" (es la base de todo)\n• Elegí dificultad "Fácil" para empezar\n\n¿Querés que te explique algún tema en particular mientras tanto? Podés preguntarme sobre OSPF, subnetting, VLANs, STP, ACLs... ¡lo que necesites! 🚀';
    }

        var recommendation = '';
    if (weakest && weakest.status === 'needs-work') {
      if (Lang.isEn()) {
        recommendation = '🔴 **Focus on ' + weakName + '** — it\'s your weakest area (' + (weakest.pct || '?') + '%). This topic covers ' + (weakest.pct || '?') + '% of the exam.';
      } else {
        recommendation = '🔴 **Enfocate en ' + weakName + '** — es tu área más débil (' + (weakest.pct || '?') + '%). Este tema representa el ' + (weakest.pct || '?') + '% del examen.';
      }
    } else {
      if (Lang.isEn()) {
        recommendation = '📈 **Doing well.** Consider taking a full practice exam to measure yourself under time pressure.';
      } else {
        recommendation = '📈 **Vas bien.** Considerá hacer un simulacro completo para medirte bajo presión de tiempo.';
      }
    }

    if (Lang.isEn()) {
      return 'Based on your performance (' + overallPct + '% on ' + totalAnswered + ' questions), I\'d recommend:\n\n' + recommendation + '\n\n**Topics you can ask me about:**\n• \"How does OSPF work?\" — \"Explain subnetting\" — \"VLANs and trunking\"\n• \"How do I configure an ACL?\" — \"Port Security\" — \"DHCP Snooping\"\n• \"Differences between TCP and UDP\" — \"What is STP?\" — \"EtherChannel\"\n\nWhat would you like to dive into? 🤓';
    }
    return 'Basado en tu desempeño (' + overallPct + '% en ' + totalAnswered + ' preguntas), te recomendaría:\n\n' + recommendation + '\n\n**Temas sobre los que podés preguntarme:**\n• \"¿Cómo funciona OSPF?\" — \"Explícame subnetting\" — \"VLANs y trunking\"\n• \"¿Cómo configuro una ACL?\" — \"Port Security\" — \"DHCP Snooping\"\n• \"Diferencias entre TCP y UDP\" — \"¿Qué es STP?\" — \"EtherChannel\"\n\n¿En qué querés profundizar? 🤓';  }
};

if (typeof window !== 'undefined') {
  window.Tutor = Tutor;
}
